//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeadHunter.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseDataType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaseDataType()
        {
            this.SourceDataType = new HashSet<SourceDataType>();
        }
    
        public int BaseDataTypeId { get; set; }
        public Nullable<bool> BaseDataTypeFlag { get; set; }
        public string BaseDataTypeName { get; set; }
        public string BaseDataTypeCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SourceDataType> SourceDataType { get; set; }
    }
}
