//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeadHunter.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceDataType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SourceDataType()
        {
            this.ProfileMeta = new HashSet<ProfileMeta>();
            this.ProfileScore = new HashSet<ProfileScore>();
        }
    
        public int SourceDataTypeId { get; set; }
        public Nullable<bool> SourceDataTypeFlag { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> BasaDataTypeId { get; set; }
        public string SourceDataTypeName { get; set; }
        public Nullable<double> ScoreMultiple { get; set; }
    
        public virtual BaseDataType BaseDataType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileMeta> ProfileMeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileScore> ProfileScore { get; set; }
        public virtual Source Source { get; set; }
    }
}
